### ISSUE TITLE
As a registered user, I want to be able to contact the admins so I can effectively communicate with them.

### ISSUE THREAD

**Issue by mayaviust** [atlantadoulaconnect/adc-app#20]

**Comment by rstrozensky** [comment]
Q1: Should the admin contact be default on the contact screen for messaging?
Q2: Can a user message an admin before being paired with a doula or before their application is approved?
Q3: Who is the default admin contact?

**Comment by mayaviust** [comment]
Backend: client user only has access to the admin who's flagged as the default contact for clients

**Comment by mayaviust** [comment]
Answered in the 2/4 client meeting.
