### ISSUE TITLE
As an admin, I want an email when a new expectant mother or doula signs up so that I can be informed of their application.

### ISSUE THREAD

**Issue by amitej** [atlantadoulaconnect/adc-app#42]

**Comment by mayaviust** [comment]
Attempted to send an email through the app but we are on Firebase's Spark plan (the free tier) which prohibits us from sending out emails using a third party unless we turn on billing. The only email actions supported by Firebase natively are emails to reset email, verify user, and recover email.

Another solution we can try turning on billing or see if we can implement SMS messaging completely free.
